name: Push-to-EC2

on:
  push:
    branches:
      - master  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH Key Install on git ubuntu:latest
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect SSH Terminal and Execute Pull GitHub Commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "-----------Rsynce------------"
          rsync -avzhe "ssh -i aws.pem" docker.sh  ubuntu@13.201.85.38:/home/ubuntu

            echo "All Tasks Sucessfully Run..!!! Thanks...... Good Byy!!!......... "
          EOF
