name: Push_Code_EC2
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.EC_PRI_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: pull 
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "----- Changing Directory -----"
            cd ${{ secrets.WORK_DIR }}

            echo "----- Git Pull -----"
            git pull origin ${{ secrets.MAIN_BRANCH }}


            echo "------Successfully-------"
