name: Push-to-EC2

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH Key Install on GitHub Ubuntu
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect SSH and Run Rsync Command
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "----------- Running Rsync Command -----------"
            rsync -avzhe "ssh -i ~/.ssh/id_ed25519" ${{ secrets.SOURCE_PATH }} ${{ secrets.SSH_USER }}@${{ secrets.RSYNC_HOST_IP }}:${{ secrets.RSYNC_DISTINATION_PATH }}
            echo "All Tasks Successfully Run..!!! Thanks...... Goodbye!!!"
          EOF
